### ISSUE TITLE
调用dialog之后，再调用微信导航相关API如wx.navigateTo，会导致新页面空白

### ISSUE THREAD

**Issue by ding-xu** [youzan/zanui-weapp#289]
环境： zanui-3.0.x的demo

步骤：1.从主页面点击进入dialog页面；
2.随便点击一个dialog;
3.返回上一页；
4.再次点击进入dialog页面；

如下图：
![image](https://user-images.githubusercontent.com/26400116/40759716-dd0529d0-64c5-11e8-9426-4c79b7436c5a.png)

![image](https://user-images.githubusercontent.com/26400116/40759746-f7accbd0-64c5-11e8-8e67-5dd79e5c0f1c.png)

![image](https://user-images.githubusercontent.com/26400116/40759764-0907d83e-64c6-11e8-84ec-8affbe7a437b.png)
 
出现渲染层错误，并且页面显示空白：

`webviewScriptError
Expect FLOW_CREATE_NODE but get another
Error: Expect FLOW_CREATE_NODE but get another
    at e.value (http://127.0.0.1:36371/__pageframe__/__dev__/WAWebview.js:20:6704)
    at http://127.0.0.1:36371/__pageframe__/__dev__/WAWebview.js:20:7041
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:36371/__pageframe__/__dev__/WAWebview.js:20:7013)
    at e.value (http://127.0.0.1:36371/__pageframe__/__dev__/WAWebview.js:20:2581)
    at Function.p._advancedCreate (http://127.0.0.1:36371/__pageframe__/__dev__/WAWebview.js:6:16133)
    at l.createComponent (http://127.0.0.1:36371/__pageframe__/__dev__/WAWebview.js:6:22603)
    at e.value (http://127.0.0.1:36371/__pageframe__/__dev__/WAWebview.js:20:5997)
    at http://127.0.0.1:36371/__pageframe__/__dev__/WAWebview.js:20:7041
    at Array.forEach (<anonymous>)`

**Comment by LY1993** [comment]
同样遇到了。很坑这个问题

**Comment by lukeyan** [comment]
我也是遇到同样的情况，官方有没有解决的方式呢？

**Comment by rex-zsd** [comment]
感觉是微信自定义组件的bug，开发者社区有挺多[反馈](https://developers.weixin.qq.com/search?action=list&t=search/index&blogcategory=511&search_type=1&key=Expect%20FLOW_CREATE_NODE%20but%20get%20another&token=&lang=zh_CN)了。稍候会提个pr绕过这个问题
