### ISSUE TITLE
在运行npm run dev 的时候报了exception

### ISSUE THREAD

**Issue by Kisen-Chin** [youzan/zanui-weapp#315]
1.git clone你们最新的代码
2.按照步骤npm install
3.npm run dev
结果报了下面的错
```
npm install
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump

> fsevents@1.2.4 install /Users/shshenhx/Desktop/zanui-weapp/node_modules/fsevents
> node install

[fsevents] Success: "/Users/shshenhx/Desktop/zanui-weapp/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> chromedriver@2.40.0 install /Users/shshenhx/Desktop/zanui-weapp/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.40/chromedriver_mac64.zip
Saving to /var/folders/f5/3rpj8x2116b51dc3mf04_2mh0000gn/T/chromedriver/chromedriver_mac64.zip
Received 781K...
Received 1576K...
Received 2360K...
Received 3144K...
Received 3928K...
Received 4712K...
Received 5496K...
Received 5532K total.
Extracting zip contents
Copying to target path /Users/shshenhx/Desktop/zanui-weapp/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /Users/shshenhx/Desktop/zanui-weapp/node_modules/chromedriver/lib/chromedriver/chromedriver

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/shshenhx/Desktop/zanui-weapp/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

added 1913 packages from 1405 contributors and audited 38509 packages in 113.448s
found 95 vulnerabilities (2 low, 84 moderate, 8 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
SHENdeMacBook-Pro:zanui-weapp shshenhx$ npm run dev

> zanui-weapp@3.0.4 dev /Users/shshenhx/Desktop/zanui-weapp
> node scripts/build-dev.js --color

[16:28:33] Working directory changed to ~/Desktop/zanui-weapp/scripts/utils
gulp[2995]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100033dab node::Abort() [/usr/local/bin/node]
 2: 0x100032ed3 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: 0x100055494 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1001e3256 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1001e2550 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x1001e1f82 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x3dd1e2a841bd 
 8: 0x3dd1e2a8f27d 
 9: 0x3dd1e2b0b4a0 
10: 0x3dd1e2a93a09 
11: 0x3dd1e2a93a09 
/private/var/folders/f5/3rpj8x2116b51dc3mf04_2mh0000gn/T/shelljs_deeb5a075b61dc7228f6:10
    fs.writeFileSync(fname, err.code.toString());
                                     ^

TypeError: Cannot read property 'toString' of null
    at /private/var/folders/f5/3rpj8x2116b51dc3mf04_2mh0000gn/T/shelljs_deeb5a075b61dc7228f6:10:38
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:595:12)
exec: internal error
```

**Comment by rex-zsd** [comment]
环境参数可以提供一下吗 node版本什么的

**Comment by Kisen-Chin** [comment]
@rex-zsd 
$node --version
v10.5.0

**Comment by Kisen-Chin** [comment]
刚刚清空了所有的小程序配置，下载了新的zanui包，又试验了下，还是一样的错误

```
node --version
v10.5.0
SHENdeMacBook-Pro:zanui-weapp shshenhx$ npm run dev

> zanui-weapp@3.0.4 dev /Users/shshenhx/Desktop/小程序/zanui-weapp
> node scripts/build-dev.js --color

[16:46:31] Working directory changed to ~/Desktop/小程序/zanui-weapp/scripts/utils
gulp[3251]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100033dab node::Abort() [/usr/local/bin/node]
 2: 0x100032ed3 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: 0x100055494 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1001e3256 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1001e2550 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x1001e1f82 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x326cb2e841bd 
/private/var/folders/f5/3rpj8x2116b51dc3mf04_2mh0000gn/T/shelljs_87ce0562ced106919f4b:10
    fs.writeFileSync(fname, err.code.toString());
                                     ^

TypeError: Cannot read property 'toString' of null
    at /private/var/folders/f5/3rpj8x2116b51dc3mf04_2mh0000gn/T/shelljs_87ce0562ced106919f4b:10:38
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
exec: internal error

```

**Comment by rex-zsd** [comment]
node@10 对 gulp@3.9 有bug，可以关注一下[#20325](https://github.com/nodejs/node/issues/20325)。
换用低版本的node 或者 删除package-lock.json重新`npm install`下载新版本的gulp可以解决这个问题。

**Comment by Kisen-Chin** [comment]
@rex-zsd 
我刚刚把node变成了8 还是出现了另外一个问题
```
node -v
v8.11.3
SHENdeMacBook-Pro:zanui-weapp shshenhx$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-config-airbnb@16.1.0 requires a peer of eslint-plugin-react@^7.4.0 but none is installed. You must install peer dependencies yourself.

up to date in 7.125s
SHENdeMacBook-Pro:zanui-weapp shshenhx$ npm run dev

> zanui-weapp@3.0.4 dev /Users/shshenhx/Desktop/小程序/zanui-weapp
> node scripts/build-dev.js --color

[17:13:58] Working directory changed to ~/Desktop/小程序/zanui-weapp/scripts/utils
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/shshenhx/Desktop/小程序/zanui-weapp/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/shshenhx/Desktop/小程序/zanui-weapp/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/shshenhx/Desktop/小程序/zanui-weapp/scripts/utils/build.js:40:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by rex-zsd** [comment]
实测mac下v8.0.0和v8.11.3都没问题。
这些exception应该都是环境的原因。
尝试删下node_modules重新安装或者换node版本吧。
