### ISSUE TITLE
使用popup组件 单机打开popup层时，提示报错

### ISSUE THREAD

**Issue by best-fan** [youzan/zanui-weapp#372]
VM2977:2 webviewScriptError
Cannot read property 'offsetLeft' of undefined;[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'offsetLeft' of undefined
    at _ (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:20:7904)
    at o.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:20:9024)
    at r.safeCallback (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:5:11371)
    at r.call (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:5:11135)
    at n (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:5:13601)
    at http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:5:14155
    at s (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:5:13169)
    at Function.r.dispatchEvent (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:5:14056)
    at t (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:7:9547)
    at g (http://127.0.0.1:61352/__pageframe__/__dev__/WAWebview.js:7:10032)

**Comment by rex-zsd** [comment]
`popup` 组件内部并没有使用 `offsetLeft`，可以提供下使用的代码片段吗？

**Comment by best-fan** [comment]
找到原因了 事件层嵌套的view太多了，不是popup组件的问题
