### ISSUE TITLE
zan-row外层view绑定 事件时 触发事件时报错

### ISSUE THREAD

**Issue by best-fan** [youzan/zanui-weapp#382]
<view class='detial_infor'  bindtap='bindShowDetial' id="{{idx}}">
        <zan-row>
          
          <zan-col col="8" col-class="custom-zan-col">
            <image class='detile-nickpic' mode="scaleToFill" src="{{item.avatar}}"></image>
          </zan-col>
          
          <zan-col col="15" col-class="custom-zan-nicname">
            <zan-col col="24">
              <view class='nicname-cn'>{{item.cn}}</view>
            </zan-col>
            <view wx:if="{{idx==0}}">
              <view class='detile-sort-text'>第一名</view>
            </view>
            <view wx:else>
              <view class='detile-sort-text'>与前一名差{{allPlayerList[idx-1].total_ticket-item.total_ticket}}票</view>
            </view>
          </zan-col>
          
          <zan-col col="1" col-class="custom-zan-col">
            <view wx:if="{{idx<3}}">
              <view class='detile-sort'>
                <image class='detile-sortpic' mode="scaleToFill" src="../../../utils/images/j{{idx+1}}.png"></image>
              </view>
            </view>
            <view wx:else>
              <view class='detile-sortimg'>{{idx+1}}</view>
            </view>
          </zan-col>
        </zan-row>
        
        <view class='detile-xcpic' >
          <view class='detile-xcpic-num'>编号:{{item.No}}</view>
          <image class='detile-xcpic' mode='aspectFill' src='{{item.works}}'></image>
        </view>
      </view>
**错误代码**
Cannot read property 'offsetLeft' of undefined;[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'offsetLeft' of undefined
    at _ (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:20:7904)
    at o.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:20:9024)
    at r.safeCallback (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:5:11371)
    at r.call (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:5:11135)
    at n (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:5:13601)
    at http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:5:14155
    at s (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:5:13169)
    at Function.r.dispatchEvent (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:5:14056)
    at t (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:7:9547)
    at g (http://127.0.0.1:61192/__pageframe__/__dev__/WAWebview.js:7:10032)

**Comment by rex-zsd** [comment]
[微信开发者社区](https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=0002c47de9c208f59ce6028a25b400&highline=TypeError%3A%20Cannot%20read%20property%20%27offsetLeft%27%20of%20undefined)有人反馈过这个问题，可以参考下。
